baseURL = "https://kubesphere.io"

[params]

applyAllInOne = false
addGoogleAnalytics = true
addGoogleTag = true
hotjarTracking = true
youtubeLink = "https://www.youtube.com/c/KubeSphere"
addLinkedin = true
addTwitter = true
useSendcloud = false